BEGIN;

ALTER TABLE prospeccao_leads ADD COLUMN IF NOT EXISTS sales_status VARCHAR(20);
ALTER TABLE prospeccao_leads ADD COLUMN IF NOT EXISTS contato_nome VARCHAR(160);
ALTER TABLE prospeccao_leads ADD COLUMN IF NOT EXISTS origem_sales VARCHAR(80);
ALTER TABLE prospeccao_leads ADD COLUMN IF NOT EXISTS proxima_acao VARCHAR(240);
ALTER TABLE prospeccao_leads ADD COLUMN IF NOT EXISTS proxima_acao_em TIMESTAMPTZ;

UPDATE prospeccao_leads SET sales_status = CASE status
  WHEN 'PRIMEIRO_CONTATO' THEN 'CONTATADO' WHEN 'RESPONDEU' THEN 'RESPONDEU'
  WHEN 'REUNIAO' THEN 'DEMO' WHEN 'PROPOSTA' THEN 'PROPOSTA'
  WHEN 'CLIENTE' THEN 'CLIENTE'
  WHEN 'DESCARTADO' THEN 'PERDIDO' WHEN 'SEM_INTERESSE' THEN 'PERDIDO'
  WHEN 'CONTATO_INVALIDO' THEN 'PERDIDO' WHEN 'NAO_CONTATAR' THEN 'PERDIDO'
  ELSE 'NOVO' END WHERE sales_status IS NULL;

ALTER TABLE candidatos ADD COLUMN IF NOT EXISTS banco_talentos_aceite BOOLEAN;
ALTER TABLE candidatos ADD COLUMN IF NOT EXISTS banco_talentos_decidido_em TIMESTAMPTZ;
ALTER TABLE candidatos ADD COLUMN IF NOT EXISTS banco_talentos_origem VARCHAR(80);
ALTER TABLE candidatos ADD COLUMN IF NOT EXISTS banco_talentos_optout_em TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS candidato_talento_auditoria (
  id BIGSERIAL PRIMARY KEY, candidato_id BIGINT NOT NULL REFERENCES candidatos(id) ON DELETE CASCADE,
  aceite BOOLEAN NOT NULL, origem VARCHAR(80), alterado_por BIGINT REFERENCES app_usuarios(id) ON DELETE SET NULL,
  alterado_por_nome VARCHAR(160), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS whatsapp_flow_testes (
  id BIGSERIAL PRIMARY KEY, flow_id VARCHAR(120), destinatario VARCHAR(40), status VARCHAR(30) NOT NULL DEFAULT 'RECEBIDO',
  horario_escolhido VARCHAR(120), payload JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
